// ESLint flat config, replacing .eslintrc.json.
//
// eslint-config-next 16 requires ESLint 9+, which dropped .eslintrc in favour
// of flat config. The package ships flat config directly through subpath
// exports, so no @eslint/eslintrc compatibility shim is needed.
//
// The previous config was `{ "extends": "next/core-web-vitals" }`; this is the
// same rule set expressed in the new format, plus explicit ignores for build
// output and the generated map data.

import coreWebVitals from "eslint-config-next/core-web-vitals";

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      // Generated by scripts/generate_usmap.ts; 77KB of projected SVG paths.
      "app/lib/usmap.ts",
    ],
  },
  ...coreWebVitals,
];

export default config;
